using System.Text.Json.Serialization;

namespace Assistant.Core.Domain;

/// <summary>Identifies who authored a <see cref="Message"/>.</summary>
[JsonConverter(typeof(JsonStringEnumConverter<MessageRole>))]
public enum MessageRole
{
    /// <summary>Text the user typed, or the action the user picked.</summary>
    User = 0,

    /// <summary>A response generated by the model.</summary>
    Assistant = 1,

    /// <summary>The result of a tool call, fed back to the model.</summary>
    Tool = 2,
}
