using System.Buffers.Binary;
using System.Diagnostics;
using System.IO.Compression;
using Assistant.Core.QuickSearch;
using Assistant.Windows.Imaging;
using Assistant.Windows.Shell;
using Xunit;

namespace Assistant.Windows.Tests;

/// <summary>Reading the applications Start lists, drawing their icons and starting them (PROJECT_SPEC §4.1).</summary>
public sealed class ShellApplicationTests : IDisposable
{
    private readonly string _folder = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "assistant-app-tests-" + Guid.NewGuid().ToString("N"));

    public void Dispose()
    {
        try
        {
            Directory.Delete(_folder, recursive: true);
        }
        catch (IOException)
        {
            // A leftover temporary folder is harmless.
        }
    }

    private string MakeProgram(string name = "tool.exe")
    {
        Directory.CreateDirectory(_folder);
        var path = Path.Combine(_folder, name);
        File.WriteAllText(path, "x");
        return path;
    }

    [Fact]
    public void ADesktopProgramsIdentityNamesItsFileThroughAKnownFolderOrAFullPath()
    {
        var program = MakeProgram();
        var relative = Path.GetRelativePath(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), program);

        // {LocalAppData}\assistant-app-tests-...\tool.exe, as Start writes a program under a known folder.
        Assert.Equal(program, ApplicationLaunchId.ExecutablePath("{F1B32785-6FBA-4FCF-9D55-7B8E7F157091}\\" + relative));
        Assert.Equal(program, ApplicationLaunchId.ExecutablePath(program));
    }

    [Theory]
    [InlineData("Microsoft.WindowsCalculator_8wekyb3d8bbwe!App")]
    [InlineData("Microsoft.AutoGenerated.{5613DA6E-5844-29DC-7B58-FA08910E6764}")]
    [InlineData("uplay://launch/6100/0")]
    [InlineData("Brave")]
    [InlineData("{6D809377-6AF0-444B-8957-A3773F02200E}\\Nothing\\Here\\gone.exe")]
    [InlineData("{00000000-0000-0000-0000-000000000000}\\x.exe")]
    [InlineData("C:\\not\\there\\gone.exe")]
    [InlineData("")]
    public void AnIdentityThatNamesNoExistingProgramHasNoPath(string id) => Assert.Null(ApplicationLaunchId.ExecutablePath(id));

    [Fact]
    public void OnlyAProgramFileCountsAsOne()
    {
        Directory.CreateDirectory(_folder);
        var text = Path.Combine(_folder, "notes.txt");
        File.WriteAllText(text, "x");

        Assert.False(ApplicationLaunchId.IsProgram(text));
        Assert.False(ApplicationLaunchId.IsProgram(null));
        Assert.False(ApplicationLaunchId.IsProgram("tool.exe"));
        Assert.True(ApplicationLaunchId.IsProgram(MakeProgram()));
        Assert.Null(ApplicationLaunchId.ExecutablePath(text));
    }

    [Theory]
    [InlineData("{6D809377-6AF0-444B-8957-A3773F02200E}\\7-Zip\\7-zip.chm", true)]
    [InlineData("C:\\Program Files\\App\\readme.txt", true)]
    [InlineData("{6D809377-6AF0-444B-8957-A3773F02200E}\\7-Zip\\7zFM.exe", false)]
    [InlineData("Microsoft.WindowsCalculator_8wekyb3d8bbwe!App", false)]
    [InlineData("uplay://launch/6100/0", false)]
    [InlineData("Microsoft.Office.MSACCESS.EXE.15", false)]
    public void HelpFilesAndPagesAreNotApplications(string id, bool isDocument) => Assert.Equal(isDocument, ApplicationLaunchId.IsDocument(id));

    [Theory]
    [InlineData("Brave", true)]
    [InlineData("Microsoft.WindowsCalculator_8wekyb3d8bbwe!App", true)]
    [InlineData("{6D809377-6AF0-444B-8957-A3773F02200E}\\7-Zip\\7zFM.exe", true)]
    [InlineData("", false)]
    [InlineData("  ", false)]
    [InlineData("a\"b", false)]
    [InlineData("a\nb", false)]
    [InlineData("..\\evil", false)]
    [InlineData("x\\..\\evil", false)]
    [InlineData("x\\..", false)]
    public void OnlyASingleCleanIdentityIsHandedToTheShell(string id, bool allowed)
    {
        var started = new List<ProcessStartInfo>();
        var launcher = new ShellApplicationLauncher(info =>
        {
            started.Add(info);
            return true;
        });

        Assert.Equal(allowed, launcher.Launch(id));

        if (allowed)
        {
            var info = Assert.Single(started);
            Assert.Equal("shell:AppsFolder\\" + id, info.FileName);
            Assert.True(info.UseShellExecute);
        }
        else
        {
            Assert.Empty(started);
        }
    }

    [Fact]
    public void ALauncherThatTheShellRefusesIsAFailureAndNeverAnException()
    {
        var launcher = new ShellApplicationLauncher(_ => throw new System.ComponentModel.Win32Exception(2));

        Assert.False(launcher.Launch("Brave"));
    }

    [Fact]
    public void APictureIsWrittenAsAPngThatHoldsItsPixelsAndItsTransparency()
    {
        // Two by two: opaque red, half-transparent blue (as it is stored, multiplied by alpha: 128 of 255), clear, opaque green.
        byte[] bgra =
        [
            0, 0, 255, 255, /**/ 128, 0, 0, 128,
            0, 0, 0, 0, /**/ 0, 255, 0, 255,
        ];

        var png = IconPng.Encode(bgra, 2, 2, premultiplied: true);

        var (width, height, rows) = ReadPng(png);
        Assert.Equal((2, 2), (width, height));

        // Each row: a filter byte, then red, green, blue and alpha of each pixel, the colors as a PNG holds them (not multiplied by alpha):
        // the half-transparent blue is full blue at alpha 128.
        Assert.Equal(
            new byte[] { 0, 255, 0, 0, 255, 0, 0, 255, 128, /**/ 0, 0, 0, 0, 0, 0, 255, 0, 255 },
            rows);
    }

    [Fact]
    public void APictureWithColorsThatAreNotMultipliedIsWrittenAsItIs()
    {
        byte[] bgra = [10, 20, 30, 100];

        var (_, _, rows) = ReadPng(IconPng.Encode(bgra, 1, 1, premultiplied: false));

        Assert.Equal([0, 30, 20, 10, 100], rows);
    }

    [Fact]
    public void APictureOfTheWrongSizeIsRefused()
    {
        Assert.Throws<ArgumentException>(() => IconPng.Encode(new byte[7], 1, 2, premultiplied: false));
        Assert.Throws<ArgumentOutOfRangeException>(() => IconPng.Encode([], 0, 1, premultiplied: false));
    }

    // The pictures of the apps that were really read: nothing is started and nothing is saved, only what the shell says is read.
    [Fact]
    public async Task TheRealAppsFolderListsTheApplicationsStartShowsWithTheirIcons()
    {
        using var source = new ShellApplicationSource(watchStartMenu: false);
        var clock = Stopwatch.StartNew();

        var applications = await source.GetApplicationsAsync(CancellationToken.None);

        Assert.NotEmpty(applications);
        Assert.All(applications, application =>
        {
            Assert.False(string.IsNullOrWhiteSpace(application.Id));
            Assert.False(string.IsNullOrWhiteSpace(application.DisplayName));
            Assert.False(ApplicationLaunchId.IsDocument(application.Id));
            if (application.ExecutablePath is { } path)
            {
                Assert.True(ApplicationLaunchId.IsProgram(path), "A path that is given names a program that exists.");
            }
        });
        Assert.Equal(applications.Count, applications.Select(application => application.Id).Distinct(StringComparer.OrdinalIgnoreCase).Count());
        Assert.True(clock.Elapsed < TimeSpan.FromSeconds(20), "Reading the applications took far too long.");

        // Calculator is a packaged app on every Windows 11 PC, and Notepad a program or a packaged app.
        Assert.Contains(applications, application => application.Id.StartsWith("Microsoft.WindowsCalculator_", StringComparison.OrdinalIgnoreCase));

        var icons = new ShellApplicationIconSource();
        var drawn = 0;
        var seenTransparency = false;
        foreach (var application in applications.Take(12))
        {
            var png = await icons.GetIconAsync(application.Id, CancellationToken.None);
            if (png is null)
            {
                continue;
            }

            drawn++;
            var (width, height, rows) = ReadPng(png);
            Assert.Equal(ShellApplicationIconSource.IconSize, width);
            Assert.Equal(ShellApplicationIconSource.IconSize, height);
            for (var offset = 0; offset < rows.Length; offset += (width * 4) + 1)
            {
                for (var x = 0; x < width; x++)
                {
                    seenTransparency |= rows[offset + 1 + (x * 4) + 3] < 255;
                }
            }

            if (Environment.GetEnvironmentVariable("ASSISTANT_ICON_DIR") is { Length: > 0 } directory)
            {
                Directory.CreateDirectory(directory);
                File.WriteAllBytes(Path.Combine(directory, $"icon-{drawn:00}.png"), png);
            }
        }

        Assert.True(drawn >= 6, "Most applications have an icon the shell can draw.");
        Assert.True(seenTransparency, "An icon keeps its transparency.");
        Assert.Null(await icons.GetIconAsync("no such application \u2603", CancellationToken.None));
    }

    // Reads a PNG: checks its signature and each chunk's checksum, and returns its size and its unpacked rows (filter byte first).
    private static (int Width, int Height, byte[] Rows) ReadPng(byte[] png)
    {
        Assert.Equal([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A], png[..8]);
        var position = 8;
        int width = 0, height = 0;
        using var data = new MemoryStream();
        while (position < png.Length)
        {
            var length = (int)BinaryPrimitives.ReadUInt32BigEndian(png.AsSpan(position));
            var type = System.Text.Encoding.ASCII.GetString(png, position + 4, 4);
            var body = png.AsSpan(position + 8, length);
            var stored = BinaryPrimitives.ReadUInt32BigEndian(png.AsSpan(position + 8 + length));
            Assert.Equal(Crc32(png.AsSpan(position + 4, 4 + length)), stored);
            if (type == "IHDR")
            {
                width = (int)BinaryPrimitives.ReadUInt32BigEndian(body);
                height = (int)BinaryPrimitives.ReadUInt32BigEndian(body[4..]);
                Assert.Equal(8, body[8]);
                Assert.Equal(6, body[9]);
            }
            else if (type == "IDAT")
            {
                data.Write(body);
            }

            position += 12 + length;
            if (type == "IEND")
            {
                break;
            }
        }

        Assert.Equal(png.Length, position);
        data.Position = 0;
        using var inflated = new ZLibStream(data, CompressionMode.Decompress);
        using var rows = new MemoryStream();
        inflated.CopyTo(rows);
        return (width, height, rows.ToArray());
    }

    private static uint Crc32(ReadOnlySpan<byte> bytes)
    {
        var crc = 0xFFFFFFFFu;
        foreach (var value in bytes)
        {
            crc ^= value;
            for (var k = 0; k < 8; k++)
            {
                crc = (crc & 1) != 0 ? 0xEDB88320u ^ (crc >> 1) : crc >> 1;
            }
        }

        return crc ^ 0xFFFFFFFFu;
    }
}
